### ISSUE TITLE
Typos in the README

### ISSUE THREAD

**Issue by iam-py-test** [punishell/bbtips#3]
I noticed a few typos in the README:
On line [5](https://github.com/punishell/bbtips/blob/master/README.md?plain=1#L5), _company_ is misspelled 
On line [6](https://github.com/punishell/bbtips/blob/master/README.md?plain=1#L6), _register_ is misspelled
On line [8](https://github.com/punishell/bbtips/blob/master/README.md?plain=1#L8), _finding_ is misspelled

If you want, I can submit a PR to fix these typos.
Thank you for providing this. If you want, I can submit a PR to fix these typos.

**Comment by punishell** [comment]
thanks :) done

pon., 18 paź 2021 o 22:30 iam-py-test ***@***.***> napisał(a):
